#!/usr/bin/env python3
"""Build deterministic generated documentation indexes."""

from __future__ import annotations

import argparse
from pathlib import Path

try:
    from ._common import ROOT, first_heading, load_yaml, parse_frontmatter
except ImportError:  # Direct script execution.
    from _common import ROOT, first_heading, load_yaml, parse_frontmatter


def render_index(root: Path = ROOT) -> str:
    """Render docs/INDEX.md from the agent map and active task packets."""
    agent_map = load_yaml(root / "docs/agent-map.yaml")
    documents = agent_map.get("documents", {})
    grouped: dict[str, list[tuple[str, str, str, str]]] = {
        "Critical": [],
        "Recommended": [],
        "Optional": [],
    }

    for relative, config in documents.items():
        path = root / relative
        metadata, body = parse_frontmatter(path)
        priority = config["priority"]
        grouped[priority].append(
            (
                relative.removeprefix("docs/"),
                first_heading(body, path.stem),
                str(metadata.get("doc_type", "unknown")),
                str(metadata.get("status", "unknown")),
            )
        )

    lines = [
        "---",
        "id: documentation-index",
        "doc_type: reference",
        "status: active",
        "authority: generated",
        "owners: [travel-platform]",
        "applies_to: [docs/**]",
        "load_when: [documentation-index]",
        "source_paths: [docs/agent-map.yaml]",
        "---",
        "",
        "<!-- Generated by scripts/docs/build_indexes.py; do not edit manually. -->",
        "",
        "# Wanderlisted documentation",
        "",
        "Start with root and nearest `AGENTS.md`, then use `agent-map.yaml` or "
        '`make docs-context PATHS="<path>"` to load only relevant documents.',
        "",
        "## Read order",
        "",
    ]
    for index, item in enumerate(agent_map.get("read_order", []), start=1):
        lines.append(f"{index}. `{item}`")

    for priority in ("Critical", "Recommended", "Optional"):
        lines.extend(
            [
                "",
                f"## {priority} documents",
                "",
                "| Document | Type | Status |",
                "|---|---|---|",
            ]
        )
        for relative, title, doc_type, status in sorted(grouped[priority]):
            lines.append(f"| [{title}]({relative}) | `{doc_type}` | `{status}` |")

    active_tasks = sorted((root / "docs/tasks/active").glob("*/TASK.md"))
    lines.extend(["", "## Active task packets", ""])
    if active_tasks:
        for path in active_tasks:
            relative = path.relative_to(root / "docs").as_posix()
            _, body = parse_frontmatter(path)
            lines.append(f"- [{first_heading(body, path.parent.name)}]({relative})")
    else:
        lines.append("No active task packet.")

    lines.extend(
        [
            "",
            "## Governance",
            "",
            "- Metadata schema: [`_schema/document.schema.json`](_schema/document.schema.json)",
            "- Templates: [`_templates/`](_templates/)",
            "- Architecture decisions: [`adr/README.md`](adr/README.md)",
            "- Business traceability: [`traceability.yaml`](traceability.yaml)",
            "- Validation: `make docs-check`",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="Fail when docs/INDEX.md is stale."
    )
    args = parser.parse_args()
    destination = ROOT / "docs/INDEX.md"
    expected = render_index()
    current = destination.read_text(encoding="utf-8") if destination.exists() else ""
    if args.check:
        if current != expected:
            print("docs/INDEX.md is stale; run make docs-index")
            return 1
        print("docs/INDEX.md is current")
        return 0
    destination.write_text(expected, encoding="utf-8")
    print(f"wrote {destination.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
